###3.3 다차원 배열의 계산

In [19]:
#3.3.1. 다차원 배열
import numpy as np
A = np.array([1, 2, 3, 4])
print(A)
print(np.ndim(A))
print(A.shape)
A.shape[0]

[1 2 3 4]
1
(4,)


4

In [20]:
B = np.array([ [1, 2], [3, 4], [5, 6] ])
print(B)
print(np.ndim(B))
B.shape

[[1 2]
 [3 4]
 [5 6]]
2


(3, 2)

In [21]:
#3.3.2. 행렬의 곱
A = np.array([ [1, 2], [3, 4] ])
B = np.array([[5, 6], [7, 8] ])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [22]:
A = np.array([ [1, 2, 3],[4, 5, 6] ]) #2x3
B = np.array([ [1, 2], [3, 4], [5, 6]]) #3x2
np.dot(A, B) #2x2

array([[22, 28],
       [49, 64]])

### 3.4. 3층 신경망 구현하기

In [23]:
X=np.array([1.0, 0.5])
W1 = np.array([ [0.1, 0.3, 0.5], [0.2, 0.4, 0.6] ])
B1 = np.array([0.1, 0.2, 0.3])
print(W1.shape)
print(X.shape)
print(B1.shape)
A1 = np.dot(X, W1) + B1
print(A1)

(2, 3)
(2,)
(3,)
[0.3 0.7 1.1]


In [24]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
Z1 = sigmoid(A1)
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])
print(Z1.shape)
print(W2.shape)
print(B2.shape)
A2 = np.dot(Z1, W2)+B2
Z2 = sigmoid(A2)
print(Z2)

(3,)
(3, 2)
(2,)
[0.62624937 0.7710107 ]


In [25]:
def identity_F(x):
    return x
W3 = np.array([ [0.1, 0.3], [0.2, 0.4] ])
B3 = np.array([ 0.1, 0.2])
A3 = np.dot(Z2, W3)+B3
Y = identity_F(A3)
Y

array([0.31682708, 0.69627909])

### 3.5 출력층 설계

In [26]:
def init_network():
    network = {}
    network['w1']=np.array([ [0.1, 0.3, 0.5], [0.2, 0.4, 0.6] ])
    network['b1']=np.array([0.1, 0.2, 0.3])
    
    network['w2']=np.array([ [0.1, 0.4], [0.2, 0.5], [0.3, 0.6] ])
    network['b2']=np.array([0.1, 0.2])

    network['w3']=np.array([ [0.1, 0.3], [0.2, 0.4] ])
    network['b3']=np.array([0.1, 0.2])
    return network

def forward(network, x): #OR의 결과값을 AND 연산시킴
    w1, w2, w3 = network['w1'], network['w2'], network['w3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    a1=np.dot(x, w1) + b1
    z1=sigmoid(a1)
    a2=np.dot(z1, w2) + b2
    z2=sigmoid(a2)
    a3=np.dot(z2, w3) + b3
    z3=sigmoid(a3)
    y = identity_F(a3)
    return y
network = init_network()
x=np.array([1.0, 0.5])
y=forward(network, x)
print(y)

[0.31682708 0.69627909]


In [27]:
#3.5.1. 소프트맥스 함수 구현
a = np.array([0.3, 2.9, 4.0])
exp_a = np.exp(a)
print(exp_a)

sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

y = exp_a / sum_exp_a
print(y)

"""def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a"""

[ 1.34985881 18.17414537 54.59815003]
74.1221542101633
[0.01821127 0.24519181 0.73659691]


'def softmax(a):\n    exp_a = np.exp(a)\n    sum_exp_a = np.sum(exp_a)\n    y = exp_a / sum_exp_a'

In [28]:
#3.5.2. 소프트맥스 함수 구현 시 주의사항
#softmax = 지수승 -> 입력 거대 = 오버플로우
#=> "이새끼 죽었는데요??"
#ㄴ 분모, 분자에 C라는 값을 곱해줌 => 오버플로우 억제

In [29]:
a=np.array([750, 749, 748])
np.exp(a)/np.sum(np.exp(a))

C:\Users\user\AppData\Local\Temp\ipykernel_1608\621028965.py:2: RuntimeWarning: overflow encountered in exp
  np.exp(a)/np.sum(np.exp(a))
C:\Users\user\AppData\Local\Temp\ipykernel_1608\621028965.py:2: RuntimeWarning: invalid value encountered in divide
  np.exp(a)/np.sum(np.exp(a))


array([nan, nan, nan])

In [30]:
def softmax(a):
    c = np.max(a)
    a-c
    y = np.exp(a-c) / np.sum(np.exp(a-c))
    return y
a = np.array( [0.3, 2.9, 4.0])
y = softmax(a)
print(y)

[0.01821127 0.24519181 0.73659691]


###3.6 손글씨 숫자 인식

In [51]:
#3.6.1 MNIST 데이터셋
from datasetsub.mnist import load_mnist
(x_train, t_train), (x_test, t_test) = load_mnist(flatten=True, normalize=False)
print(x_train.shape)
print(t_train.shape)
print(x_test.shape)
print(t_test.shape)

(60000, 784)
(60000,)
(10000, 784)
(10000,)


In [14]:
import numpy as np
from PIL import  Image
img = x_train[0]
label = t_train[0]
print(label)
print(img.shape)
img = img.reshape(28, 28)
print(img.shape)
pil_img = Image.fromarray(np.uint8(img))
pil_img

5
(784,)
(28, 28)


In [15]:
import pickle
def sigmoid(x):
    return 1/(1+np.exp(-x))
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np. sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [16]:
def get_data():
    (x_train, t_train), (x_test, t_test) = load_mnist(
        normalize=True, flatten=True, one_hot_label=False)
    return x_test, t_test
def init_network():
    with open("sample_weight.pkl", 'rb') as f:
        network = pickle.load(f)
    return network
def predict(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    a1=np.dot(x, W1) + b1
    z1=sigmoid(a1)
    a2=np.dot(z1, W2) + b2
    z2=sigmoid(a2)
    a3=np.dot(z2, W3) + b3
    y = softmax(a3)
    return y

In [17]:
import time
x, t = get_data()
st = time.time()
network = init_network()
accuracy_cnt = 0
for i in range( len(x) ):
    y = predict(network, x[i])
    p = np.argmax(y)
    if p == t[i]:
        accuracy_cnt += 1
end = time.time() - st
print('Accuracy: ' + str(float(accuracy_cnt) / len(x)))
end

Accuracy: 0.9352


0.2621612548828125

In [18]:
#10000장을 100장씩 100번 조지기
batch_size = 100
accuracy_cnt = 0
st2 = time.time()
for i in range(0, len(x), batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = predict(network, x_batch)
    p = np.argmax(y_batch, axis=1)
    accuracy_cnt += np.sum(p == t[i:i+batch_size])
end2 = time.time() - st2
print("Accuracy: " + str(float(accuracy_cnt) / len(x)))
print(end2)

Accuracy: 0.9352
0.09438467025756836
